# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Master

on:
  push:
    branches:
    - master


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
      with:        
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x


    - uses: dotnet/nbgv@master
      id: nbgv
    - name: Set Package Version
      run: |
          echo "NugetPackageVersion=${{ steps.nbgv.outputs.SimpleVersion }}-ci.${{ steps.nbgv.outputs.VersionRevision }}" >> "$GITHUB_ENV"
    - name: Set Package Version
      if: startsWith(github.ref, 'refs/heads/develop')
      run: |
          echo "NugetPackageVersion=${{ steps.nbgv.outputs.SimpleVersion }}-alpha.${{ steps.nbgv.outputs.VersionRevision }}" >> "$GITHUB_ENV"
    - name: Set Package Version
      if: startsWith(github.ref, 'refs/heads/release')
      run: |
          echo "NugetPackageVersion=${{ steps.nbgv.outputs.SimpleVersion }}-beta.${{ steps.nbgv.outputs.VersionRevision }}" >> "$GITHUB_ENV"
    - name: Set Package Version
      if: startsWith(github.ref, 'refs/heads/master')
      run: |
          echo "NugetPackageVersion=${{ steps.nbgv.outputs.SimpleVersion }}" >> "$GITHUB_ENV"
    - name: Diplay Package Version
      run: echo "PackageVersion=${{ env.NugetPackageVersion }}"



    - name: Restore dependencies
      run: dotnet restore src/IdentityServer8.sln
    - name: Build
      run: dotnet build src/IdentityServer8.sln --configuration Release --no-restore -p:Version=${{ steps.nbgv.outputs.SimpleVersion }}-ci.${{ steps.nbgv.outputs.VersionRevision }}
    - name: Test
      run: dotnet test src/IdentityServer8.sln --configuration Release --no-build --verbosity normal


    - name: Push
      if: ${{ (github.event_name == 'push') && (runner.os == 'Windows') }} 
      run: dotnet nuget push .\nuget\*.nupkg  --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

